### ISSUE TITLE
CodeQL Initialize Actions fail on Push Events

### ISSUE THREAD

**Issue by tillkuhn** [dbschenker/vaultpal#20]
Dependabot Pipelines fail if triggered by Push events, since CodeQL Initialize Actions run into errors (see [example](https://github.com/dbschenker/vaultpal/actions/runs/5226625945/jobs/9437468334?pr=19#step:15:47)). While we could probably extend the workflow permissions,  the error messages simply suggest to use code scanning on pull_request events only. @pschulten WDYT?

```
Error: Workflows triggered by Dependabot on the "push" event run with read-only access. Uploading Code Scanning results requires write access. 

To use Code Scanning with Dependabot, please ensure you are using the "pull_request" event for this workflow and avoid triggering on the "push" event for Dependabot branches. 

See https://docs.github.com/en/code-security/secure-coding/configuring-code-scanning#scanning-on-push for more information on how to configure these events.
```

**Comment by pschulten** [comment]
done
